import type { CallingNumber } from "./CallingNumberTable";

export const MOCK_CALLING_NUMBERS: CallingNumber[] = [
  {
    id: 1,
    phoneNumber: "02-1234-5678",
    name: "고객센터 대표번호",
    registeredAt: "2025-01-10T09:00:00",
    certExpiredAt: "2026-01-10T09:00:00",
    status: "정상",
    usageEnabled: true,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_위즈온.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-1234-5678.pdf",
      },
      { label: "위임장", fileName: "위임장_고객센터.docx" },
      { label: "대표자 신분증", fileName: "신분증_사본.jpg" },
    ],
    requestNote: "고객센터 안내 발송 및 설문조사 안내용으로 사용합니다.",
  },
  {
    id: 2,
    phoneNumber: "010-9876-5432",
    name: "마케팅팀 번호",
    registeredAt: "2025-03-05T11:00:00",
    certExpiredAt: "2026-03-05T11:00:00",
    status: "반려",
    usageEnabled: false,
    rejectReason:
      "통신 서비스 이용증명원의 발신번호와 신청 발신번호가 일치하지 않습니다. 정확한 번호가 기재된 이용증명원을 재첨부해주세요.",
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_위즈온.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_010-9876-5432.pdf",
      },
    ],
    requestNote: "마케팅 캠페인 문자 발송용",
  },
  {
    id: 3,
    phoneNumber: "031-555-7777",
    name: "경기지사 번호",
    registeredAt: "2024-12-20T14:00:00",
    certExpiredAt: "2025-12-20T14:00:00",
    status: "만료",
    usageEnabled: false,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_경기지사.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_031-555-7777.pdf",
      },
      { label: "위임장", fileName: "위임장_경기지사.pdf" },
      { label: "재직증명서", fileName: "재직증명서_홍길동.pdf" },
    ],
  },
  {
    id: 4,
    phoneNumber: "02-8888-1234",
    name: "신규 신청 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "검수중",
    usageEnabled: false,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_위즈온.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-8888-1234.pdf",
      },
      { label: "위임장", fileName: "위임장_신규.docx" },
      { label: "대표자 신분증", fileName: "신분증_사본.jpg" },
    ],
    requestNote: "신규 서비스 론칭 안내 발송 예정",
  },
  {
    id: 5,
    phoneNumber: "02-8888-1234",
    name: "공공기관 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "정상",
    usageEnabled: true,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_공공기관.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-8888-1234.pdf",
      },
      { label: "위임장", fileName: "위임장_공공기관.pdf" },
      { label: "재직증명서", fileName: "재직증명서_김철수.pdf" },
    ],
    requestNote: "공공기관 설문 안내 및 결과 통보용",
  },
  {
    id: 6,
    phoneNumber: "02-1111-1111",
    name: "테스트 신청 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "정상",
    usageEnabled: false,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_공공기관.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-1111-1111.pdf",
      },
      { label: "위임장", fileName: "위임장_공공기관.pdf" },
      { label: "재직증명서", fileName: "재직증명서_김철수.pdf" },
    ],
    requestNote: "공공기관 설문 안내 및 결과 통보용",
  },
  {
    id: 7,
    phoneNumber: "02-1111-1112",
    name: "테스트 신청 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "정상",
    usageEnabled: true,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_공공기관.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-1111-1112.pdf",
      },
      { label: "위임장", fileName: "위임장_공공기관.pdf" },
      { label: "재직증명서", fileName: "재직증명서_김철수.pdf" },
    ],
    requestNote: "공공기관 설문 안내 및 결과 통보용",
  },
  {
    id: 8,
    phoneNumber: "02-1111-1113",
    name: "테스트 신청 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "정상",
    usageEnabled: true,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_공공기관.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-1111-1113.pdf",
      },
      { label: "위임장", fileName: "위임장_공공기관.pdf" },
      { label: "재직증명서", fileName: "재직증명서_김철수.pdf" },
    ],
    requestNote: "공공기관 설문 안내 및 결과 통보용",
  },
  {
    id: 9,
    phoneNumber: "02-1111-1114",
    name: "테스트 신청 번호",
    registeredAt: "2026-03-20T10:00:00",
    certExpiredAt: "2027-03-20T10:00:00",
    status: "정상",
    usageEnabled: true,
    attachments: [
      { label: "사업자 등록증", fileName: "사업자등록증_공공기관.pdf" },
      {
        label: "통신 서비스 이용증명원",
        fileName: "이용증명원_02-1111-1114.pdf",
      },
      { label: "위임장", fileName: "위임장_공공기관.pdf" },
      { label: "재직증명서", fileName: "재직증명서_김철수.pdf" },
    ],
    requestNote: "공공기관 설문 안내 및 결과 통보용",
  },
];
